### ISSUE TITLE
Unpickling python2 crated binary file. 

### ISSUE THREAD

**Issue by GeorgeS2019** [irmen/pickle#1]
It is known that pickle fine created by python2 may not be loaded by python3 using "pickle.load" 
Could your solution unpickle a binary file created by python2 involving Numpy arrays?

**Comment by irmen** [comment]
No, numpy arrays are pickled in a specialized format that is not readable by other programs at all.
(This has nothing to do with python 2 or python 3)
There has been some discussion about this in the past, see https://github.com/irmen/Pyrolite/issues/52
