### ISSUE TITLE
Unpickle failed on __builtin__ bytes with no arguments

### ISSUE THREAD

**Issue by bkats** [irmen/pickle#11]
Got an exception saying that constructor needs 1 or 2 arguments but got 0 on load_reduce of a byte array.
Pickle file is as follows:
    0: \x80 PROTO      2
    2: }    EMPTY_DICT
    3: q    BINPUT     0
    5: (    MARK
    6: X        BINUNICODE 'modules/ATL.rpymc'
   28: q        BINPUT     1
   30: ]        EMPTY_LIST
   31: q        BINPUT     2
   33: J        BININT     1111638641
   38: J        BININT     1111622394
   43: c        GLOBAL     '__builtin__ bytes'
   62: q        BINPUT     3
   64: )        EMPTY_TUPLE
   65: R        REDUCE
   66: q        BINPUT     4
   68: \x87     TUPLE3
   69: q        BINPUT     5
   71: a        APPEND

**Comment by irmen** [comment]
how was the pickle created? what Python version is used?

**Comment by bkats** [comment]
The pickle was created by Ren'Py 8.1 using Python 3.9
I have also attached the complete pickle
[dirlist.zip](https://github.com/irmen/pickle/files/11479372/dirlist.zip)

**Comment by irmen** [comment]
Oh, what version are you using that gives the error?  Java or .NET?  (or maybe both).

**Comment by bkats** [comment]
Sorry to forget to mention it, but .NET

**Comment by irmen** [comment]
Ok I think I fixed this in badc8fe08c9e47b87df66b8a16c67010e3614e35

can you try it to see if it gives satisfactory results now? If so I shall release an updated version.

**Comment by bkats** [comment]
That works for me. Only you did not update the exception text for the .net variant.

This issue can be closed, but I gone add at least one more. Now I got a missing class __builtin__ frozenset, but there might be more so I will first go through the stuff further before I open a new issue.

**Comment by irmen** [comment]
I updated the error message text now.
I'll hold off making a new release for a while so we can try to fix other errors you might run into (weird, it seems some details have changed in the pickle data format in recent python versions perhaps....)  , but I'll close this issue.

**Comment by irmen** [comment]
published new 1.4 release.
