### ISSUE TITLE
Upper unicode points not supported

### ISSUE THREAD

**Issue by platnumkid** [irmen/pickle#2]
net.razorvine.pickle.PickleException: invalid escape sequence char 'U' in string "seth rollins \U0001f455 [...]" (possibly truncated)

Python pickles any unicode char above \uffff to \U0001xxxx.  
decode_unicode_escaped() doesn't currently support
`case: 'U'`
and throws.  Can this support be added?

**Comment by irmen** [comment]
I'll see what I can do, sounds like a simple fix. Thanks for reporting.

**Comment by irmen** [comment]
@platnumkid  in the meantime, don't use pickle protocol 0.  Try using one of the recent protocols. For instance on Python3.8 we're at protocol 4. These encode differently and more efficiently.

**Comment by platnumkid** [comment]
Thanks!

**Comment by irmen** [comment]
Just released pickle 1.1  java and .net version, with the \U fix .
