### ISSUE TITLE
seems cannot load compressed file

### ISSUE THREAD

**Issue by BlueD** [irmen/pickle#5]
I'm using pandas to save a dataframe with 'xz' compression.

```python
df.to_pickle("abc.pickle", compression="xz")
```
and the `dotnet` version threw an exception while loading it.

```
Unhandled exception. Razorvine.Pickle.InvalidOpcodeException: invalid pickle opcode: 253
```

**Comment by irmen** [comment]
Well, yeah, a compressed pickle isn't a pickle byte stream. You'll have to decompress it first.

**Comment by BlueD** [comment]
You are right. Ok, Thanks.
