### ISSUE TITLE
Decimal('NaN') is unsupported in Java unpickling

### ISSUE THREAD

**Issue by Yikun** [irmen/pickle#7]
Looks like decimal('NaN') is unsupported in net.razorvine.pickle:

### Python pickle
```Python
# float('NaN') can be picled and loaded
>>> pickled = cloudpickle.dumps(float('NaN'))
>>> pickle.loads(pickled)
nan

# Decimal('NaN') can be pickled and loaded
>>> pickled = cloudpickle.dumps(decimal.Decimal('NaN'))
b'\x80\x05\x95!\x00\x00\x00\x00\x00\x00\x00\x8c\x07decimal\x94\x8c\x07Decimal\x94\x93\x94\x8c\x03NaN\x94\x85\x94R\x94.'
>>> pickle.loads(pickled)
Decimal('NaN')
```

### Java net.razorvine.pickle
float('NaN')  can be loaded as exepected
```Scala
scala> unpickle.loads(PickleUtils.str2bytes("\u0080\u0005\u0095\n\u0000\u0000\u0000\u0000\u0000\u0000\u0000G\u007f\u00f8\u0000\u0000\u0000\u0000\u0000\u0000."))

Object = NaN
```

But Decimal('NaN') can NOT be loaded with java.lang.reflect.InvocationTargetException

```Scala
scala> unpickle.loads(PickleUtils.str2bytes("\u0080\u0005\u0095!\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u008c\u0007decimal\u0094\u008c\u0007Decimal\u0094\u0093\u0094\u008c\u0003NaN\u0094\u0085\u0094R\u0094."))
net.razorvine.pickle.PickleException: problem construction object: java.lang.reflect.InvocationTargetException
  at net.razorvine.pickle.objects.AnyClassConstructor.construct(AnyClassConstructor.java:29)
  at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:773)
  at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:213)
  at net.razorvine.pickle.Unpickler.load(Unpickler.java:123)
  at net.razorvine.pickle.Unpickler.loads(Unpickler.java:136)
  ... 48 elided

```

After some investigation, I found, as pointed from https://github.com/irmen/pickle/blob/master/README.md#python-to-java-unpickling , the decimal is mapped to java BigDecimal, but accroing to [java doc](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html) the BigDecimal can't be `NaN`.

Do you have any idea for fixing it, Thanks!

Related: [SPARK-36000](https://issues.apache.org/jira/browse/SPARK-36000) cc @HyukjinKwon @xinrong-databricks

**Comment by irmen** [comment]
We can't make BigDecimal represent a NaN

I guess we can :
- map it into a float NaN
- or throw a better exception (NumberFormatException?)

I'll have a look if the first option is viable. However this means that you won't always get a BigDecimal object as a result of unpickling a python decimal. However I guess a Decimal NaN occurs very infrequently and if you need to support it it should be easy enough to test the type of the resulting object.


The same issue appears in the .NET version of the code btw.

**Comment by irmen** [comment]
@Yikun

Decimal("NaN") is now unpickled as Double.NaN.   2809d25137814ea37cd9f17c566395d50d19af0f

This is now released in pickle version 1.2.

**Comment by HyukjinKwon** [comment]
Thanks all!

**Comment by Yikun** [comment]
@irmen Woow, thanks, might it posible backport this PR to https://github.com/irmen/Pyrolite and release a 4.32 version?

**Comment by irmen** [comment]
No, it would be a 5.2 version in that case because currently it's at 5.1.  But since 5.0 pickle is no longer part of Pyrolite itself.
However I believe you’re only using the pickle part of pyrolite yeah? The way forward should be, I think, to replace pyrolite by just this pickle library. ?

**Comment by xinrong-meng** [comment]
Thank you, that's very helpful!

**Comment by irmen** [comment]
@Yikun ping , not sure if you're read my reply above (because I haven't seen a change in the status of the ticked on the Spark issue tracker.)

**Comment by HyukjinKwon** [comment]
Thanks for pinging @irmen! Seems like the backport isn't an option here, seems like the way we could try here is to replace to this pickle library.

**Comment by Yikun** [comment]
@irmen Much thanks for your answer, I missed it before. And I will also try to switch `pyrolite` to `pickle` on spark upstream.

**Comment by irmen** [comment]
Yeah that should be the way to go.   I don't believe you were using any of the non pickle related functions from the ``pyrolite`` library before so I think it should be fairly straightforward to switch?

**Comment by Yikun** [comment]
I do some local test, it works! It would be fixed in https://github.com/apache/spark/pull/34285 in Spark. 

Much thanks for your awesome help! @irmen
