### ISSUE TITLE
DecimalConstructor fails when parsing decimal string using scientific notation

### ISSUE THREAD

**Issue by akamor** [irmen/pickle#8]
DecimalConstructor.cs is calling

```
Convert.ToDecimal(stringArg, CultureInfo.InvariantCulture)
```

So something like

```
System.Convert.ToDecimal("5E-1",CultureInfo.InvariantCulture)
```

Will throw a **System.FormatException: Input string was not in a correct format.** exception

This has bit us when using Microsoft.Spark (which takes this library as a dependency).  We build C# UDFs that run in Spark which requires data to be serialized back and forth between the JVM and the CLR.  In sparkland we have some decimal values that Spark decides to represent in scientific notation and when this gets pickled into the CLR we hit the above issue.

I did a bit of research and using something like

```
Decimal.Parse("5E-1, NumberStyles.AllowAny)
```

would work but is *maybe* too permissive.  I think at a minimum we would need

```
Decimal.Parse("5E-1, NumberStyles.AllowLeadingSign | NumberStyles.DecimalPoint | NumberStyles.Exponent)
```
but there might be others.

**Comment by akamor** [comment]
We were able to resolve this via registering a custom constructor which was not something I originally realized was possible.

Might still be nice to fix it in a future version of the product.  Thank you.

**Comment by irmen** [comment]
I'll look into this.

**Comment by akamor** [comment]
Thanks.  And thanks for adding the ability to add a custom constructor!  Here is our solution.  YMMV.

```
public class OverriddenDecimalConstructor : IObjectConstructor
{
    public object construct(object[] args)
    {
        if (args.Length == 1 && args[0] is string s)
        {
            if (s.ToLowerInvariant() == "nan") return double.NaN;
            //PATCH: //return Convert.ToDecimal((string)args[0], CultureInfo.InvariantCulture);
            return decimal.Parse(s, NumberStyles.Any);
        }

        throw new PickleException("invalid arguments for decimal constructor");
    }
}
```

**Comment by irmen** [comment]
Java's BigDecimal doesn't have this issue btw. But I still added a unit test for it there as well.

**Comment by irmen** [comment]
Pushed version 1.2.1 to nuget.org.
