### ISSUE TITLE
Should `put_long` use LONG1 encoding for values than Integer.MAX_VALUE?

### ISSUE THREAD

**Issue by JoshRosen** [irmen/pickle#9]
Pickler's [`put_long` method](https://github.com/irmen/pickle/blob/95e92018b5be53514ec4cfe165e39aa5837c200d/java/src/main/java/net/razorvine/pickle/Pickler.java#L710-L740) currently falls back on the text-based `INT` encoding if the long value is too large to be represented as a 4-byte signed integer.

Instead, I'm wondering whether it should use the `LONG1` encoding and write it as an 8-byte signed integer. Since this method's parameter is a `long` I think all of the values should fit in a `LONG1`. My understanding is that `LONG1` should be more time- and space-efficient for these values. Pyrolite already uses `LONG1` encoding when writing BigIntegers.

---

If I use Pyrolite to do `pickler.dumps(9223372036854775807L)` (which is Long.MAX_VALUE), pickletools disassembles the result as:

```
    0: \x80 PROTO      2
    2: I    INT        9223372036854775807
   23: .    STOP
highest protocol among opcodes = 2
```

This matches Python 2.7's behavior. 

In contrast, Python 3.7 pickles this value using `LONG1` (which requires nearly half the space):

```
>>> pickletools.dis(pickle.dumps(9223372036854775807, protocol=2))
    0: \x80 PROTO      2
    2: \x8a LONG1      9223372036854775807
   12: .    STOP
highest protocol among opcodes = 2
```

**Comment by irmen** [comment]
Agreed. If Python's protocol 2 pickle uses it, we should too.

**Comment by irmen** [comment]
this is now avaiable in Pickle release 1.3.
